// Romanian court institutions parsed from SOAP WSDL enum values.
// Auto-generated from frontend/src/lib/institutii.ts (labels diacritics-stripped
// per backend convention). Backend uses this catalog to expand SOAP enum values
// (e.g. "TribunalulBUCURESTI") to spaced labels ("Tribunalul Bucuresti") for
// export rendering — without this, PDFKit char-wraps unbreakable strings.

const ENTRIES: ReadonlyArray<readonly [string, string]> = [
  ["CurteadeApelALBAIULIA", "Curtea de Apel Alba Iulia"],
  ["CurteadeApelBACAU", "Curtea de Apel Bacau"],
  ["CurteadeApelBRASOV", "Curtea de Apel Brasov"],
  ["CurteadeApelBUCURESTI", "Curtea de Apel Bucuresti"],
  ["CurteadeApelCLUJ", "Curtea de Apel Cluj"],
  ["CurteadeApelCONSTANTA", "Curtea de Apel Constanta"],
  ["CurteadeApelCRAIOVA", "Curtea de Apel Craiova"],
  ["CurteadeApelGALATI", "Curtea de Apel Galati"],
  ["CurteadeApelIASI", "Curtea de Apel Iasi"],
  ["CurteadeApelORADEA", "Curtea de Apel Oradea"],
  ["CurteadeApelPITESTI", "Curtea de Apel Pitesti"],
  ["CurteadeApelPLOIESTI", "Curtea de Apel Ploiesti"],
  ["CurteadeApelSUCEAVA", "Curtea de Apel Suceava"],
  ["CurteadeApelTARGUMURES", "Curtea de Apel Targu Mures"],
  ["CurteadeApelTIMISOARA", "Curtea de Apel Timisoara"],
  ["TribunalulALBA", "Tribunalul Alba"],
  ["TribunalulARAD", "Tribunalul Arad"],
  ["TribunalulARGES", "Tribunalul Arges"],
  ["TribunalulBACAU", "Tribunalul Bacau"],
  ["TribunalulBIHOR", "Tribunalul Bihor"],
  ["TribunalulBISTRITANASAUD", "Tribunalul Bistrita-Nasaud"],
  ["TribunalulBOTOSANI", "Tribunalul Botosani"],
  ["TribunalulBRAILA", "Tribunalul Braila"],
  ["TribunalulBRASOV", "Tribunalul Brasov"],
  ["TribunalulBUCURESTI", "Tribunalul Bucuresti"],
  ["TribunalulBUZAU", "Tribunalul Buzau"],
  ["TribunalulCALARASI", "Tribunalul Calarasi"],
  ["TribunalulCARASSEVERIN", "Tribunalul Caras-Severin"],
  ["TribunalulCLUJ", "Tribunalul Cluj"],
  ["TribunalulCONSTANTA", "Tribunalul Constanta"],
  ["TribunalulCOVASNA", "Tribunalul Covasna"],
  ["TribunalulDAMBOVITA", "Tribunalul Dambovita"],
  ["TribunalulDOLJ", "Tribunalul Dolj"],
  ["TribunalulGALATI", "Tribunalul Galati"],
  ["TribunalulGIURGIU", "Tribunalul Giurgiu"],
  ["TribunalulGORJ", "Tribunalul Gorj"],
  ["TribunalulHARGHITA", "Tribunalul Harghita"],
  ["TribunalulHUNEDOARA", "Tribunalul Hunedoara"],
  ["TribunalulIALOMITA", "Tribunalul Ialomita"],
  ["TribunalulIASI", "Tribunalul Iasi"],
  ["TribunalulILFOV", "Tribunalul Ilfov"],
  ["TribunalulMARAMURES", "Tribunalul Maramures"],
  ["TribunalulMEHEDINTI", "Tribunalul Mehedinti"],
  ["TribunalulMURES", "Tribunalul Mures"],
  ["TribunalulNEAMT", "Tribunalul Neamt"],
  ["TribunalulOLT", "Tribunalul Olt"],
  ["TribunalulPRAHOVA", "Tribunalul Prahova"],
  ["TribunalulSALAJ", "Tribunalul Salaj"],
  ["TribunalulSATUMARE", "Tribunalul Satu Mare"],
  ["TribunalulSIBIU", "Tribunalul Sibiu"],
  ["TribunalulSUCEAVA", "Tribunalul Suceava"],
  ["TribunalulTELEORMAN", "Tribunalul Teleorman"],
  ["TribunalulTIMIS", "Tribunalul Timis"],
  ["TribunalulTULCEA", "Tribunalul Tulcea"],
  ["TribunalulVALCEA", "Tribunalul Valcea"],
  ["TribunalulVASLUI", "Tribunalul Vaslui"],
  ["TribunalulVRANCEA", "Tribunalul Vrancea"],
  ["TribunalulpentruminoriSifamilieBRASOV", "Tribunalul pentru Minori si Familie Brasov"],
  ["TribunalulComercialARGES", "Tribunalul Comercial Arges"],
  ["TribunalulComercialCLUJ", "Tribunalul Comercial Cluj"],
  ["TribunalulComercialMURES", "Tribunalul Comercial Mures"],
  ["TribunalulMilitarBUCURESTI", "Tribunalul Militar Bucuresti"],
  ["TribunalulMilitarCLUJNAPOCA", "Tribunalul Militar Cluj-Napoca"],
  ["TribunalulMilitarIASI", "Tribunalul Militar Iasi"],
  ["TribunalulMilitarTIMISOARA", "Tribunalul Militar Timisoara"],
  ["TribunalulMilitarTeritorialBUCURESTI", "Tribunalul Militar Teritorial Bucuresti"],
  ["CurteaMilitaradeApelBUCURESTI", "Curtea Militara de Apel Bucuresti"],
  ["JudecatoriaADJUD", "Judecatoria Adjud"],
  ["JudecatoriaAGNITA", "Judecatoria Agnita"],
  ["JudecatoriaAIUD", "Judecatoria Aiud"],
  ["JudecatoriaALBAIULIA", "Judecatoria Alba Iulia"],
  ["JudecatoriaALESD", "Judecatoria Alesd"],
  ["JudecatoriaALEXANDRIA", "Judecatoria Alexandria"],
  ["JudecatoriaARAD", "Judecatoria Arad"],
  ["JudecatoriaAVRIG", "Judecatoria Avrig"],
  ["JudecatoriaBABADAG", "Judecatoria Babadag"],
  ["JudecatoriaBACAU", "Judecatoria Bacau"],
  ["JudecatoriaBAIADEARAMA", "Judecatoria Baia de Arama"],
  ["JudecatoriaBAIAMARE", "Judecatoria Baia Mare"],
  ["JudecatoriaBAILESTI", "Judecatoria Bailesti"],
  ["JudecatoriaBALCESTI", "Judecatoria Balcesti"],
  ["JudecatoriaBALS", "Judecatoria Bals"],
  ["JudecatoriaBARLAD", "Judecatoria Barlad"],
  ["JudecatoriaBECLEAN", "Judecatoria Beclean"],
  ["JudecatoriaBEIUS", "Judecatoria Beius"],
  ["JudecatoriaBICAZ", "Judecatoria Bicaz"],
  ["JudecatoriaBISTRITA", "Judecatoria Bistrita"],
  ["JudecatoriaBLAJ", "Judecatoria Blaj"],
  ["JudecatoriaBOLINTINVALE", "Judecatoria Bolintin-Vale"],
  ["JudecatoriaBOTOSANI", "Judecatoria Botosani"],
  ["JudecatoriaBOZOVICI", "Judecatoria Bozovici"],
  ["JudecatoriaBRAD", "Judecatoria Brad"],
  ["JudecatoriaBRAILA", "Judecatoria Braila"],
  ["JudecatoriaBRASOV", "Judecatoria Brasov"],
  ["JudecatoriaBREZOI", "Judecatoria Brezoi"],
  ["JudecatoriaBUFTEA", "Judecatoria Buftea"],
  ["JudecatoriaBUHUSI", "Judecatoria Buhusi"],
  ["JudecatoriaBUZAU", "Judecatoria Buzau"],
  ["JudecatoriaCALAFAT", "Judecatoria Calafat"],
  ["JudecatoriaCALARASI", "Judecatoria Calarasi"],
  ["JudecatoriaCAMPENI", "Judecatoria Campeni"],
  ["JudecatoriaCAMPINA", "Judecatoria Campina"],
  ["JudecatoriaCAMPULUNG", "Judecatoria Campulung"],
  ["JudecatoriaCAMPULUNGMOLDOVENESC", "Judecatoria Campulung Moldovenesc"],
  ["JudecatoriaCARACAL", "Judecatoria Caracal"],
  ["JudecatoriaCARANSEBES", "Judecatoria Caransebes"],
  ["JudecatoriaCAREI", "Judecatoria Carei"],
  ["JudecatoriaCHISINEUCRIS", "Judecatoria Chisineu-Cris"],
  ["JudecatoriaCLUJNAPOCA", "Judecatoria Cluj-Napoca"],
  ["JudecatoriaCONSTANTA", "Judecatoria Constanta"],
  ["JudecatoriaCORABIA", "Judecatoria Corabia"],
  ["JudecatoriaCORNETU", "Judecatoria Cornetu"],
  ["JudecatoriaCOSTESTI", "Judecatoria Costesti"],
  ["JudecatoriaCRAIOVA", "Judecatoria Craiova"],
  ["JudecatoriaCURTEADEARGES", "Judecatoria Curtea de Arges"],
  ["JudecatoriaDarabani", "Judecatoria Darabani"],
  ["JudecatoriaDEJ", "Judecatoria Dej"],
  ["JudecatoriaDETA", "Judecatoria Deta"],
  ["JudecatoriaDEVA", "Judecatoria Deva"],
  ["JudecatoriaDOROHOI", "Judecatoria Dorohoi"],
  ["JudecatoriaDRAGASANI", "Judecatoria Dragasani"],
  ["JudecatoriaDRAGOMIRESTI", "Judecatoria Dragomiresti"],
  ["JudecatoriaDROBETATURNUSEVERIN", "Judecatoria Drobeta-Turnu Severin"],
  ["JudecatoriaFAGARAS", "Judecatoria Fagaras"],
  ["JudecatoriaFAGET", "Judecatoria Faget"],
  ["JudecatoriaFALTICENI", "Judecatoria Falticeni"],
  ["JudecatoriaFAUREI", "Judecatoria Faurei"],
  ["JudecatoriaFETESTI", "Judecatoria Fetesti"],
  ["JudecatoriaFILIASI", "Judecatoria Filiasi"],
  ["JudecatoriaFOCSANI", "Judecatoria Focsani"],
  ["JudecatoriaGAESTI", "Judecatoria Gaesti"],
  ["JudecatoriaGALATI", "Judecatoria Galati"],
  ["JudecatoriaGHEORGHENI", "Judecatoria Gheorgheni"],
  ["JudecatoriaGHERLA", "Judecatoria Gherla"],
  ["JudecatoriaGIURGIU", "Judecatoria Giurgiu"],
  ["JudecatoriaGURAHONT", "Judecatoria Gurahont"],
  ["JudecatoriaGURAHUMORULUI", "Judecatoria Gura Humorului"],
  ["JudecatoriaHARLAU", "Judecatoria Harlau"],
  ["JudecatoriaHARSOVA", "Judecatoria Harsova"],
  ["JudecatoriaHATEG", "Judecatoria Hateg"],
  ["JudecatoriaHOREZU", "Judecatoria Horezu"],
  ["JudecatoriaHUEDIN", "Judecatoria Huedin"],
  ["JudecatoriaHUNEDOARA", "Judecatoria Hunedoara"],
  ["JudecatoriaHUSI", "Judecatoria Husi"],
  ["JudecatoriaIASI", "Judecatoria Iasi"],
  ["JudecatoriaINEU", "Judecatoria Ineu"],
  ["JudecatoriaINSURATEI", "Judecatoria Insuratei"],
  ["JudecatoriaINTORSURABUZAULUI", "Judecatoria Intorsura Buzaului"],
  ["JudecatoriaJIBOU", "Judecatoria Jibou"],
  ["JudecatoriaLEHLIUGARA", "Judecatoria Lehliu-Gara"],
  ["JudecatoriaLIESTI", "Judecatoria Liesti"],
  ["JudecatoriaLIPOVA", "Judecatoria Lipova"],
  ["JudecatoriaLUDUS", "Judecatoria Ludus"],
  ["JudecatoriaLUGOJ", "Judecatoria Lugoj"],
  ["JudecatoriaMACIN", "Judecatoria Macin"],
  ["JudecatoriaMANGALIA", "Judecatoria Mangalia"],
  ["JudecatoriaMARGHITA", "Judecatoria Marghita"],
  ["JudecatoriaMEDGIDIA", "Judecatoria Medgidia"],
  ["JudecatoriaMEDIAS", "Judecatoria Medias"],
  ["JudecatoriaMIERCUREACIUC", "Judecatoria Miercurea Ciuc"],
  ["JudecatoriaMIZIL", "Judecatoria Mizil"],
  ["JudecatoriaMOINESTI", "Judecatoria Moinesti"],
  ["JudecatoriaMOLDOVANOUA", "Judecatoria Moldova Noua"],
  ["JudecatoriaMORENI", "Judecatoria Moreni"],
  ["JudecatoriaMOTRU", "Judecatoria Motru"],
  ["JudecatoriaMURGENI", "Judecatoria Murgeni"],
  ["JudecatoriaNASAUD", "Judecatoria Nasaud"],
  ["JudecatoriaNEGRESTIOAS", "Judecatoria Negresti-Oas"],
  ["JudecatoriaNOVACI", "Judecatoria Novaci"],
  ["JudecatoriaODORHEIULSECUIESC", "Judecatoria Odorheiu Secuiesc"],
  ["JudecatoriaOLTENITA", "Judecatoria Oltenita"],
  ["JudecatoriaONESTI", "Judecatoria Onesti"],
  ["JudecatoriaORADEA", "Judecatoria Oradea"],
  ["JudecatoriaORASTIE", "Judecatoria Orastie"],
  ["JudecatoriaORAVITA", "Judecatoria Oravita"],
  ["JudecatoriaORSOVA", "Judecatoria Orsova"],
  ["JudecatoriaPANCIU", "Judecatoria Panciu"],
  ["JudecatoriaPASCANI", "Judecatoria Pascani"],
  ["JudecatoriaPATARLAGELE", "Judecatoria Patarlagele"],
  ["JudecatoriaPETROSANI", "Judecatoria Petrosani"],
  ["JudecatoriaPIATRANEAMT", "Judecatoria Piatra Neamt"],
  ["JudecatoriaPITESTI", "Judecatoria Pitesti"],
  ["JudecatoriaPLOIESTI", "Judecatoria Ploiesti"],
  ["JudecatoriaPODUTURCULUI", "Judecatoria Podu Turcului"],
  ["JudecatoriaPOGOANELE", "Judecatoria Pogoanele"],
  ["JudecatoriaPUCIOASA", "Judecatoria Pucioasa"],
  ["JudecatoriaRACARI", "Judecatoria Racari"],
  ["JudecatoriaRADAUTI", "Judecatoria Radauti"],
  ["JudecatoriaRADUCANENI", "Judecatoria Raducaneni"],
  ["JudecatoriaRAMNICUSARAT", "Judecatoria Ramnicu Sarat"],
  ["JudecatoriaRAMNICUVALCEA", "Judecatoria Ramnicu Valcea"],
  ["JudecatoriaREGHIN", "Judecatoria Reghin"],
  ["JudecatoriaRESITA", "Judecatoria Resita"],
  ["JudecatoriaROMAN", "Judecatoria Roman"],
  ["JudecatoriaROSIORIDEVEDE", "Judecatoria Rosiori de Vede"],
  ["JudecatoriaRUPEA", "Judecatoria Rupea"],
  ["JudecatoriaSALISTE", "Judecatoria Saliste"],
  ["JudecatoriaSALONTA", "Judecatoria Salonta"],
  ["JudecatoriaSANNICOLAULMARE", "Judecatoria Sannicolau Mare"],
  ["JudecatoriaSATUMARE", "Judecatoria Satu Mare"],
  ["JudecatoriaSAVENI", "Judecatoria Saveni"],
  ["JudecatoriaSEBES", "Judecatoria Sebes"],
  ["JudecatoriaSECTORUL1BUCURESTI", "Judecatoria Sectorul 1 Bucuresti"],
  ["JudecatoriaSECTORUL2BUCURESTI", "Judecatoria Sectorul 2 Bucuresti"],
  ["JudecatoriaSECTORUL3BUCURESTI", "Judecatoria Sectorul 3 Bucuresti"],
  ["JudecatoriaSECTORUL4BUCURESTI", "Judecatoria Sectorul 4 Bucuresti"],
  ["JudecatoriaSECTORUL5BUCURESTI", "Judecatoria Sectorul 5 Bucuresti"],
  ["JudecatoriaSECTORUL6BUCURESTI", "Judecatoria Sectorul 6 Bucuresti"],
  ["JudecatoriaSEGARCEA", "Judecatoria Segarcea"],
  ["JudecatoriaSFANTUGHEORGHE", "Judecatoria Sfantu Gheorghe"],
  ["JudecatoriaSIBIU", "Judecatoria Sibiu"],
  ["JudecatoriaSIGHETUMARMATIEI", "Judecatoria Sighetu Marmatiei"],
  ["JudecatoriaSIGHISOARA", "Judecatoria Sighisoara"],
  ["JudecatoriaSIMLEULSILVANIEI", "Judecatoria Simleu Silvaniei"],
  ["JudecatoriaSINAIA", "Judecatoria Sinaia"],
  ["JudecatoriaSLATINA", "Judecatoria Slatina"],
  ["JudecatoriaSLOBOZIA", "Judecatoria Slobozia"],
  ["JudecatoriaSOMCUTAMARE", "Judecatoria Somcuta Mare"],
  ["JudecatoriaSTREHAIA", "Judecatoria Strehaia"],
  ["JudecatoriaSUCEAVA", "Judecatoria Suceava"],
  ["JudecatoriaTARGOVISTE", "Judecatoria Targoviste"],
  ["JudecatoriaTARGUBUJOR", "Judecatoria Targu Bujor"],
  ["JudecatoriaTARGUCARBUNESTI", "Judecatoria Targu Carbunesti"],
  ["JudecatoriaTARGUJIU", "Judecatoria Targu Jiu"],
  ["JudecatoriaTARGULAPUS", "Judecatoria Targu Lapus"],
  ["JudecatoriaTARGUMURES", "Judecatoria Targu Mures"],
  ["JudecatoriaTARGUNEAMT", "Judecatoria Targu Neamt"],
  ["JudecatoriaTARGUSECUIESC", "Judecatoria Targu Secuiesc"],
  ["JudecatoriaTARNAVENI", "Judecatoria Tarnaveni"],
  ["JudecatoriaTECUCI", "Judecatoria Tecuci"],
  ["JudecatoriaTIMISOARA", "Judecatoria Timisoara"],
  ["JudecatoriaTOPLITA", "Judecatoria Toplita"],
  ["JudecatoriaTOPOLOVENI", "Judecatoria Topoloveni"],
  ["JudecatoriaTULCEA", "Judecatoria Tulcea"],
  ["JudecatoriaTURDA", "Judecatoria Turda"],
  ["JudecatoriaTURNUMAGURELE", "Judecatoria Turnu Magurele"],
  ["JudecatoriaURZICENI", "Judecatoria Urziceni"],
  ["JudecatoriaVALENIIDEMUNTE", "Judecatoria Valenii de Munte"],
  ["JudecatoriaVANJUMARE", "Judecatoria Vanju Mare"],
  ["JudecatoriaVASLUI", "Judecatoria Vaslui"],
  ["JudecatoriaVATRADORNEI", "Judecatoria Vatra Dornei"],
  ["JudecatoriaVIDELE", "Judecatoria Videle"],
  ["JudecatoriaVISEUDESUS", "Judecatoria Viseu de Sus"],
  ["JudecatoriaZALAU", "Judecatoria Zalau"],
  ["JudecatoriaZARNESTI", "Judecatoria Zarnesti"],
  ["JudecatoriaZIMNICEA", "Judecatoria Zimnicea"],
];

const _normalizeCache = new Map<string, string>();
let _lookupBuilt = false;

function _buildKey(s: string): string {
  return s
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/\s+/g, "")
    .toLowerCase();
}

function _ensureLookup() {
  if (_lookupBuilt) return;
  for (const [value, label] of ENTRIES) {
    _normalizeCache.set(_buildKey(label), label);
    _normalizeCache.set(_buildKey(value), label);
  }
  _lookupBuilt = true;
}

export function normalizeInstitutie(raw: string): string {
  if (!raw) return raw;
  _ensureLookup();
  return _normalizeCache.get(_buildKey(raw)) ?? raw;
}

// Catalogul complet de token-uri SOAP (enum-ul WSDL), pentru fan-out-ul tolerant
// din cautarea de dosare cand apelul agregat PortalJust esueaza. Inghetat: e
// sursa unica, nimeni nu are voie sa-l mute la runtime.
const _tokens: readonly string[] = Object.freeze(ENTRIES.map(([value]) => value));

export function allInstitutionTokens(): readonly string[] {
  return _tokens;
}
